% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\title{Statistical Genetics - practical 1}
\author{}
\date{\vspace{-2.5em}}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Statistical Genetics - practical 1},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\begin{document}
\maketitle

install.packages(``data.table'')

\hypertarget{for-mac-do-this-first}{%
\section{for mac do this first:}\label{for-mac-do-this-first}}

install.packages(``Rsolnp'', type = ``binary'') \#\#

install.packages(``HardyWeinberg'')

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(data.table)}
\FunctionTok{library}\NormalTok{(HardyWeinberg)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: mice
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'mice'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:stats':
## 
##     filter
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     cbind, rbind
\end{verbatim}

\begin{verbatim}
## Loading required package: nnet
\end{verbatim}

\begin{verbatim}
## Loading required package: Rsolnp
\end{verbatim}

\begin{verbatim}
## Loading required package: shape
\end{verbatim}

\hypertarget{snp-dataset}{%
\section{SNP dataset}\label{snp-dataset}}

\hypertarget{loading-dataset}{%
\subsection{Loading dataset}\label{loading-dataset}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{read.table}\NormalTok{(}\StringTok{"TSICHR22RAW.raw"}\NormalTok{, }\AttributeTok{header =} \ConstantTok{TRUE}\NormalTok{)}

\NormalTok{genetic\_info }\OtherTok{\textless{}{-}}\NormalTok{ df[, }\DecValTok{7}\SpecialCharTok{:}\FunctionTok{ncol}\NormalTok{(df)]}

\NormalTok{geno\_dt }\OtherTok{\textless{}{-}} \FunctionTok{as.data.table}\NormalTok{(genetic\_info)}
\end{Highlighting}
\end{Shaded}

\hypertarget{how-many-variants-are-there-in-this-database-what-percentage-of-the-data-is-missing}{%
\subsection{1. How many variants are there in this database? What
percentage of the data is
missing?}\label{how-many-variants-are-there-in-this-database-what-percentage-of-the-data-is-missing}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n\_variants }\OtherTok{\textless{}{-}} \FunctionTok{ncol}\NormalTok{(geno\_dt)}

\FunctionTok{cat}\NormalTok{(}\StringTok{"Number of variants:"}\NormalTok{, n\_variants, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Number of variants: 20649
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pct\_missing }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(geno\_dt)) }\SpecialCharTok{*} \DecValTok{100}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Percentage missing:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(pct\_missing, }\DecValTok{2}\NormalTok{), }\StringTok{"\%}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Percentage missing: 0.2 %
\end{verbatim}

\hypertarget{calculate-the-percentage-of-monomorphic-variants.-exclude-all-monomorphics-from-the-database-for-all-posterior-computations-of-the-practical.-how-many-variants-do-remain-in-your-database}{%
\subsection{2. Calculate the percentage of monomorphic variants. Exclude
all monomorphics from the database for all posterior computations of the
practical. How many variants do remain in your
database?}\label{calculate-the-percentage-of-monomorphic-variants.-exclude-all-monomorphics-from-the-database-for-all-posterior-computations-of-the-practical.-how-many-variants-do-remain-in-your-database}}

Monomorphic means no variation, so we look for columns with same value
all accross.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n\_unique }\OtherTok{\textless{}{-}}\NormalTok{ geno\_dt[, }\FunctionTok{sapply}\NormalTok{(.SD, }\ControlFlowTok{function}\NormalTok{(x) }\FunctionTok{uniqueN}\NormalTok{(}\FunctionTok{na.omit}\NormalTok{(x)))]}
\NormalTok{monomorphic }\OtherTok{\textless{}{-}}\NormalTok{ n\_unique }\SpecialCharTok{\textless{}=} \DecValTok{1}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Monomorphic \%:"}\NormalTok{, }\FunctionTok{mean}\NormalTok{(monomorphic) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Monomorphic %: 11.45818
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{geno\_poly }\OtherTok{\textless{}{-}}\NormalTok{ geno\_dt[, }\SpecialCharTok{!}\NormalTok{monomorphic, with }\OtherTok{=} \ConstantTok{FALSE}\NormalTok{]}

\NormalTok{n\_poly }\OtherTok{\textless{}{-}} \FunctionTok{ncol}\NormalTok{(geno\_poly)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Remaining variants:"}\NormalTok{, n\_poly, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Remaining variants: 18283
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Removed variants:"}\NormalTok{, }\FunctionTok{ncol}\NormalTok{(geno\_dt)}\SpecialCharTok{{-}}\NormalTok{n\_poly, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Removed variants: 2366
\end{verbatim}

\hypertarget{report-the-genotype-counts-and-the-minor-allele-count-of-polymorphism-rs8138488-c-and-calculate-the-maf-of-this-variant.}{%
\subsection{3. Report the genotype counts and the minor allele count of
polymorphism rs8138488 C, and calculate the MAF of this
variant.}\label{report-the-genotype-counts-and-the-minor-allele-count-of-polymorphism-rs8138488-c-and-calculate-the-maf-of-this-variant.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{geno\_counts }\OtherTok{\textless{}{-}}\NormalTok{ geno\_poly[, .N, by }\OtherTok{=}\NormalTok{ rs8138488\_C]}
\FunctionTok{print}\NormalTok{(geno\_counts)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    rs8138488_C     N
##          <int> <int>
## 1:           0    41
## 2:           1    47
## 3:           2    14
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# genotype counts}
\NormalTok{g0 }\OtherTok{\textless{}{-}}\NormalTok{ geno\_poly[rs8138488\_C }\SpecialCharTok{==} \DecValTok{0}\NormalTok{, .N]}
\NormalTok{g1 }\OtherTok{\textless{}{-}}\NormalTok{ geno\_poly[rs8138488\_C }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, .N]}
\NormalTok{g2 }\OtherTok{\textless{}{-}}\NormalTok{ geno\_poly[rs8138488\_C }\SpecialCharTok{==} \DecValTok{2}\NormalTok{, .N]}

\CommentTok{\# allel counts}
\NormalTok{n\_ref }\OtherTok{\textless{}{-}} \DecValTok{2} \SpecialCharTok{*}\NormalTok{ g0 }\SpecialCharTok{+}\NormalTok{ g1}
\NormalTok{n\_alt }\OtherTok{\textless{}{-}} \DecValTok{2} \SpecialCharTok{*}\NormalTok{ g2 }\SpecialCharTok{+}\NormalTok{ g1}
\NormalTok{n\_total }\OtherTok{\textless{}{-}}\NormalTok{ n\_ref }\SpecialCharTok{+}\NormalTok{ n\_alt}

\CommentTok{\# allele frequencies}
\NormalTok{freq\_ref }\OtherTok{\textless{}{-}}\NormalTok{ n\_ref }\SpecialCharTok{/}\NormalTok{ n\_total}
\NormalTok{freq\_alt }\OtherTok{\textless{}{-}}\NormalTok{ n\_alt }\SpecialCharTok{/}\NormalTok{ n\_total}

\CommentTok{\# MAF}
\NormalTok{MAF }\OtherTok{\textless{}{-}} \FunctionTok{min}\NormalTok{(freq\_ref, freq\_alt)}

\FunctionTok{cat}\NormalTok{(}\StringTok{"Genotype counts:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Genotype counts:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  0 (AA):"}\NormalTok{, g0, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   0 (AA): 41
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  1 (AB):"}\NormalTok{, g1, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   1 (AB): 47
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  2 (BB):"}\NormalTok{, g2, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   2 (BB): 14
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Allele counts:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Allele counts:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  Reference:"}\NormalTok{, n\_ref, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Reference: 129
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  Alternate:"}\NormalTok{, n\_alt, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Alternate: 75
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Allele frequencies:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Allele frequencies:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  Reference:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(freq\_ref, }\DecValTok{4}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Reference: 0.6324
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  Alternate:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(freq\_alt, }\DecValTok{4}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Alternate: 0.3676
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"MAF:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(MAF, }\DecValTok{4}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## MAF: 0.3676
\end{verbatim}

\hypertarget{compute-the-minor-allele-frequencies-maf-for-all-markers-and-make-a-histogram-of-it.-does-the-maf-follow-a-uniform-distribution-what-percentage-of-the-markers-have-a-maf-below-0.05-and-below-0.01-can-you-explain-the-observed-pattern-uniform-distribution-at-0-0.5.-the-range-from-0-to-0.5-can-be-easily-explained-due-to-the-fact-that-a-frequency-higher-than-0.5-would-indicate-this-is-not-the-minor-allele.}{%
\subsection{4. Compute the minor allele frequencies (MAF) for all
markers, and make a histogram of it. Does the MAF follow a uniform
distribution? What percentage of the markers have a MAF below 0.05? And
below 0.01? Can you explain the observed pattern? Uniform distribution
at {[}0, 0.5{]}. The range from 0 to 0.5 can be easily explained due to
the fact that a frequency higher than 0.5 would indicate this is not the
minor
allele.}\label{compute-the-minor-allele-frequencies-maf-for-all-markers-and-make-a-histogram-of-it.-does-the-maf-follow-a-uniform-distribution-what-percentage-of-the-markers-have-a-maf-below-0.05-and-below-0.01-can-you-explain-the-observed-pattern-uniform-distribution-at-0-0.5.-the-range-from-0-to-0.5-can-be-easily-explained-due-to-the-fact-that-a-frequency-higher-than-0.5-would-indicate-this-is-not-the-minor-allele.}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Function to compute MAF for one column}
\NormalTok{compute\_maf }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) \{}
\NormalTok{  g0 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(x }\SpecialCharTok{==} \DecValTok{0}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{  g1 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(x }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{  g2 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(x }\SpecialCharTok{==} \DecValTok{2}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{  n\_ref }\OtherTok{\textless{}{-}} \DecValTok{2} \SpecialCharTok{*}\NormalTok{ g0 }\SpecialCharTok{+}\NormalTok{ g1}
\NormalTok{  n\_alt }\OtherTok{\textless{}{-}} \DecValTok{2} \SpecialCharTok{*}\NormalTok{ g2 }\SpecialCharTok{+}\NormalTok{ g1}
\NormalTok{  n\_total }\OtherTok{\textless{}{-}}\NormalTok{ n\_ref }\SpecialCharTok{+}\NormalTok{ n\_alt}
  \ControlFlowTok{if}\NormalTok{ (n\_total }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) }\FunctionTok{return}\NormalTok{(}\ConstantTok{NA}\NormalTok{)}
  \FunctionTok{min}\NormalTok{(n\_ref, n\_alt) }\SpecialCharTok{/}\NormalTok{ n\_total}
\NormalTok{\}}

\CommentTok{\# Apply to all columns}
\NormalTok{maf }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(geno\_poly, compute\_maf)}


\FunctionTok{hist}\NormalTok{(maf,}
     \AttributeTok{breaks =} \DecValTok{100}\NormalTok{,}
     \AttributeTok{col =} \StringTok{"steelblue"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Distribution of Minor Allele Frequencies"}\NormalTok{,}
     \AttributeTok{xlab =} \StringTok{"MAF"}\NormalTok{,}
     \AttributeTok{ylab =} \StringTok{"Number of variants"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{pract_1_anna_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# We can visually assess, but also Kolmogorov{-}Smirnov test against uniform too }
\FunctionTok{ks.test}\NormalTok{(maf, }\StringTok{"punif"}\NormalTok{, }\AttributeTok{min =} \DecValTok{0}\NormalTok{, }\AttributeTok{max =} \FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in ks.test(maf, "punif", min = 0, max = 0.5): ties should not be
## present for the Kolmogorov-Smirnov test
\end{verbatim}

\begin{verbatim}
## 
##  One-sample Kolmogorov-Smirnov test
## 
## data:  maf
## D = 0.06309, p-value < 2.2e-16
## alternative hypothesis: two-sided
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Below 0.05}
\NormalTok{pct\_below\_005 }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(maf }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{*} \DecValTok{100}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Percentage with MAF \textless{} 0.05:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(pct\_below\_005, }\DecValTok{2}\NormalTok{), }\StringTok{"\%}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Percentage with MAF < 0.05: 14.23 %
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Below 0.01}
\NormalTok{pct\_below\_001 }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(maf }\SpecialCharTok{\textless{}} \FloatTok{0.01}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{*} \DecValTok{100}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Percentage with MAF \textless{} 0.01:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(pct\_below\_001, }\DecValTok{2}\NormalTok{), }\StringTok{"\%}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Percentage with MAF < 0.01: 4.73 %
\end{verbatim}

Answers: Following visual analysis (L-shape of the data) and results of
the Kolmogorov-Smirnov test against uniform, we observe that the
distribution isn't uniform. What this tells us is that in this
population there are a lot of monomorphic variants (only one allele).

14.23 \% of the variants have MAF lower than 0.05 and 4.73 \% MAF lower
than 0.01. These numbers indicate that there are around 4-14\% of
variants that happen very rarely

This means that a fraction of the variants in this population are rare
variants. The fact that the percentage drops sharply when the threshold
is lowered (from 14.23\% to 4.73\%) indicates that very rare variants
are much less common than moderately rare ones. It is most likely for a
variant to be common.

\hypertarget{calculate-the-observed-heterozygosity-h0-and-make-a-histogram-of-it.-what-is-theoretically-the-range-of-variation-of-this-statistic}{%
\subsection{5. Calculate the observed heterozygosity H0, and make a
histogram of it. What is, theoretically, the range of variation of this
statistic?}\label{calculate-the-observed-heterozygosity-h0-and-make-a-histogram-of-it.-what-is-theoretically-the-range-of-variation-of-this-statistic}}

At a given SNP, we have two chromosome copies of each parent. If those
two copies have different alleles, it is heterozygous. So code 1 =
heterozygous.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Function to compute H0 for one column}
\NormalTok{compute\_h0 }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) \{}
\NormalTok{  x }\OtherTok{\textless{}{-}}\NormalTok{ x[}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(x)]              }
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{length}\NormalTok{(x) }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) }\FunctionTok{return}\NormalTok{(}\ConstantTok{NA}\NormalTok{)}
  \FunctionTok{mean}\NormalTok{(x }\SpecialCharTok{==} \DecValTok{1}\NormalTok{)                   }
\NormalTok{\}}

\NormalTok{h0 }\OtherTok{\textless{}{-}}\NormalTok{ geno\_poly[, }\FunctionTok{lapply}\NormalTok{(.SD, }\ControlFlowTok{function}\NormalTok{(x) }\FunctionTok{mean}\NormalTok{(x }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))]}
\NormalTok{h0 }\OtherTok{\textless{}{-}} \FunctionTok{unlist}\NormalTok{(h0)}

\FunctionTok{hist}\NormalTok{(h0,}
     \AttributeTok{breaks =} \DecValTok{50}\NormalTok{,}
     \AttributeTok{col =} \StringTok{"steelblue"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Distribution of Observed Heterozygosity (H0)"}\NormalTok{,}
     \AttributeTok{xlab =} \StringTok{"H0"}\NormalTok{,}
     \AttributeTok{ylab =} \StringTok{"Number of variants"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{pract_1_anna_files/figure-latex/unnamed-chunk-7-1.pdf}
Answer:

The theoretical range of this statistic is {[}0, 1{]}, since it is
possible that all individuals are Homozygous. In practice, we are seeing
values much below 1 because it is rare for every individual in a sample
to be heterozygous.

\hypertarget{compute-for-each-marker-its-expected-heterozygosity-he.-make-a-histogram-of-the-expected-heterozygosity.-what-is-theoretically-the-range-of-variation-of-this-statistic-what-is-the-average-of-he-for-this-database}{%
\subsection{Compute for each marker its expected heterozygosity (He).
Make a histogram of the expected heterozygosity. What is, theoretically,
the range of variation of this statistic? What is the average of He for
this
database?}\label{compute-for-each-marker-its-expected-heterozygosity-he.-make-a-histogram-of-the-expected-heterozygosity.-what-is-theoretically-the-range-of-variation-of-this-statistic-what-is-the-average-of-he-for-this-database}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Function to compute He for one variant}
\NormalTok{compute\_he }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) \{}
\NormalTok{  x }\OtherTok{\textless{}{-}}\NormalTok{ x[}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(x)]}
\NormalTok{  g0 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(x }\SpecialCharTok{==} \DecValTok{0}\NormalTok{)}
\NormalTok{  g1 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(x }\SpecialCharTok{==} \DecValTok{1}\NormalTok{)}
\NormalTok{  g2 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(x }\SpecialCharTok{==} \DecValTok{2}\NormalTok{)}
  
\NormalTok{  n\_ref }\OtherTok{\textless{}{-}} \DecValTok{2} \SpecialCharTok{*}\NormalTok{ g0 }\SpecialCharTok{+}\NormalTok{ g1}
\NormalTok{  n\_alt }\OtherTok{\textless{}{-}} \DecValTok{2} \SpecialCharTok{*}\NormalTok{ g2 }\SpecialCharTok{+}\NormalTok{ g1}
\NormalTok{  n\_total }\OtherTok{\textless{}{-}}\NormalTok{ n\_ref }\SpecialCharTok{+}\NormalTok{ n\_alt}
  
  \ControlFlowTok{if}\NormalTok{ (n\_total }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) }\FunctionTok{return}\NormalTok{(}\ConstantTok{NA}\NormalTok{)}
  
\NormalTok{  p\_ref }\OtherTok{\textless{}{-}}\NormalTok{ n\_ref }\SpecialCharTok{/}\NormalTok{ n\_total}
\NormalTok{  p\_alt }\OtherTok{\textless{}{-}}\NormalTok{ n\_alt }\SpecialCharTok{/}\NormalTok{ n\_total}
  
  \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ (p\_ref}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ p\_alt}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{\}}

\NormalTok{he }\OtherTok{\textless{}{-}}\NormalTok{ geno\_poly[, }\FunctionTok{lapply}\NormalTok{(.SD, compute\_he)]}
\NormalTok{he }\OtherTok{\textless{}{-}} \FunctionTok{unlist}\NormalTok{(he)}

\FunctionTok{hist}\NormalTok{(he,}
     \AttributeTok{breaks =} \DecValTok{50}\NormalTok{,}
     \AttributeTok{col =} \StringTok{"steelblue"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Expected Heterozygosity (He)"}\NormalTok{,}
     \AttributeTok{xlab =} \StringTok{"He"}\NormalTok{,}
     \AttributeTok{ylab =} \StringTok{"Number of variants"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{pract_1_anna_files/figure-latex/unnamed-chunk-8-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Min He:"}\NormalTok{, }\FunctionTok{min}\NormalTok{(he, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Min He: 0.009755863
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Max He:"}\NormalTok{, }\FunctionTok{max}\NormalTok{(he, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Max He: 0.5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Mean He:"}\NormalTok{, }\FunctionTok{mean}\NormalTok{(he, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Mean He: 0.3115841
\end{verbatim}

Answers: The theoretical range of He is {[}0, 0.5{]}, with the maximum
occurring when both alleles are equally frequent. In this database, the
average He is 0.3116.

\hypertarget{str-dataset}{%
\section{STR dataset}\label{str-dataset}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(NistSTRs)}

\CommentTok{\# Save to a data frame}
\NormalTok{str\_df }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(NistSTRs)}
\end{Highlighting}
\end{Shaded}

\hypertarget{how-many-individuals-and-how-many-strs-contains-the-database}{%
\subsection{1. How many individuals and how many STRs contains the
database?}\label{how-many-individuals-and-how-many-strs-contains-the-database}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Individuals:"}\NormalTok{, }\FunctionTok{nrow}\NormalTok{(str\_df), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Individuals: 361
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"STRs:"}\NormalTok{, }\FunctionTok{ncol}\NormalTok{(str\_df) }\SpecialCharTok{/} \DecValTok{2}\NormalTok{, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## STRs: 29
\end{verbatim}

\hypertarget{write-a-function-that-determines-the-number-of-alleles-for-a-str.-determine-the-number-of-alleles-for-each-str-in-the-database.-compute-basic-descriptive-statistics-of-the-number-of-alleles-mean-standard-deviation-median-minimum-maximum.}{%
\subsection{2. Write a function that determines the number of alleles
for a STR. Determine the number of alleles for each STR in the database.
Compute basic descriptive statistics of the number of alleles (mean,
standard deviation, median, minimum,
maximum).}\label{write-a-function-that-determines-the-number-of-alleles-for-a-str.-determine-the-number-of-alleles-for-each-str-in-the-database.-compute-basic-descriptive-statistics-of-the-number-of-alleles-mean-standard-deviation-median-minimum-maximum.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{count\_alleles }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(allele1, allele2) \{}
\NormalTok{  all\_alleles }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(allele1, allele2)}
\NormalTok{  all\_alleles }\OtherTok{\textless{}{-}}\NormalTok{ all\_alleles[}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(all\_alleles)]}
  \FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(all\_alleles))}
\NormalTok{\}}

\NormalTok{str\_names }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(}\FunctionTok{sub}\NormalTok{(}\StringTok{"{-}1$|{-}2$"}\NormalTok{, }\StringTok{""}\NormalTok{, }\FunctionTok{colnames}\NormalTok{(str\_df)))}

\NormalTok{n\_alleles }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(str\_names, }\ControlFlowTok{function}\NormalTok{(s) \{}
  \FunctionTok{count\_alleles}\NormalTok{(str\_df[[}\FunctionTok{paste0}\NormalTok{(s, }\StringTok{"{-}1"}\NormalTok{)]], str\_df[[}\FunctionTok{paste0}\NormalTok{(s, }\StringTok{"{-}2"}\NormalTok{)]])}
\NormalTok{\})}


\FunctionTok{cat}\NormalTok{(}\StringTok{"Number of alleles per STR:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Number of alleles per STR:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(n\_alleles)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   CSF1PO D10S1248  D12S391  D13S317  D16S539   D18S51  D19S433  D1S1656 
##        7        9       16        8        7       15       15       15 
##   D21S11 D22S1045  D2S1338   D2S441  D3S1358   D5S818  D6S1043   D7S820 
##       16        8       12       11        9        9       14        9 
##  D8S1179   F13A01     F13B   FESFPS      FGA      LPL  Penta_C  Penta_D 
##       10       12        6        7       14        8       10       13 
##  Penta_E     SE33     TH01     TPOX      vWA 
##       19       39        8        8       10
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Mean:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(n\_alleles), }\DecValTok{2}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Mean: 11.86
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"SD:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{sd}\NormalTok{(n\_alleles), }\DecValTok{2}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## SD: 6.23
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Median:"}\NormalTok{, }\FunctionTok{median}\NormalTok{(n\_alleles), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Median: 10
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Min:"}\NormalTok{, }\FunctionTok{min}\NormalTok{(n\_alleles), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Min: 6
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Max:"}\NormalTok{, }\FunctionTok{max}\NormalTok{(n\_alleles), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Max: 39
\end{verbatim}

\hypertarget{make-a-table-with-the-number-of-strs-for-a-given-number-of-alleles-and-present-a-barplot-of-the-number-strs-in-each-category.-what-is-the-most-common-number-of-alleles-for-an-str}{%
\subsection{3. Make a table with the number of STRs for a given number
of alleles and present a barplot of the number STRs in each category.
What is the most common number of alleles for an
STR?}\label{make-a-table-with-the-number-of-strs-for-a-given-number-of-alleles-and-present-a-barplot-of-the-number-strs-in-each-category.-what-is-the-most-common-number-of-alleles-for-an-str}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{allele\_table }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(n\_alleles)}
\FunctionTok{print}\NormalTok{(allele\_table)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## n_alleles
##  6  7  8  9 10 11 12 13 14 15 16 19 39 
##  1  3  5  4  3  1  2  1  2  3  2  1  1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{barplot}\NormalTok{(allele\_table,}
        \AttributeTok{main =} \StringTok{"Number of STRs by Number of Alleles"}\NormalTok{,}
        \AttributeTok{xlab =} \StringTok{"Number of alleles"}\NormalTok{,}
        \AttributeTok{ylab =} \StringTok{"Number of STRs"}\NormalTok{,}
        \AttributeTok{col =} \StringTok{"steelblue"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{pract_1_anna_files/figure-latex/unnamed-chunk-12-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{most\_common }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{names}\NormalTok{(allele\_table)[}\FunctionTok{which.max}\NormalTok{(allele\_table)])}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Most common number of alleles:"}\NormalTok{, most\_common, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Most common number of alleles: 8
\end{verbatim}

\hypertarget{compute-the-expected-heterozygosity-for-each-str.-make-a-histogram-of-the-expected-heterozygosity-over-all-strs.-compute-the-average-expected-heterozygosity-over-all-strs.}{%
\subsection{4. Compute the expected heterozygosity for each STR. Make a
histogram of the expected heterozygosity over all STRS. Compute the
average expected heterozygosity over all
STRs.}\label{compute-the-expected-heterozygosity-for-each-str.-make-a-histogram-of-the-expected-heterozygosity-over-all-strs.-compute-the-average-expected-heterozygosity-over-all-strs.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{compute\_he\_str }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(allele1, allele2) \{}
\NormalTok{  all\_alleles }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(allele1, allele2)}
\NormalTok{  all\_alleles }\OtherTok{\textless{}{-}}\NormalTok{ all\_alleles[}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(all\_alleles)]}
\NormalTok{  freqs }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(all\_alleles) }\SpecialCharTok{/} \FunctionTok{length}\NormalTok{(all\_alleles)}
  \DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{sum}\NormalTok{(freqs}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{\}}

\NormalTok{str\_names }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(}\FunctionTok{sub}\NormalTok{(}\StringTok{"{-}1$|{-}2$"}\NormalTok{, }\StringTok{""}\NormalTok{, }\FunctionTok{colnames}\NormalTok{(str\_df)))}

\NormalTok{he\_str }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(str\_names, }\ControlFlowTok{function}\NormalTok{(s) \{}
  \FunctionTok{compute\_he\_str}\NormalTok{(str\_df[[}\FunctionTok{paste0}\NormalTok{(s, }\StringTok{"{-}1"}\NormalTok{)]], str\_df[[}\FunctionTok{paste0}\NormalTok{(s, }\StringTok{"{-}2"}\NormalTok{)]])}
\NormalTok{\})}

\FunctionTok{hist}\NormalTok{(he\_str, }\AttributeTok{breaks =} \DecValTok{15}\NormalTok{, }\AttributeTok{col =} \StringTok{"steelblue"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Expected Heterozygosity (He) per STR"}\NormalTok{,}
     \AttributeTok{xlab =} \StringTok{"He"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Number of STRs"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{pract_1_anna_files/figure-latex/unnamed-chunk-13-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Average He:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(he\_str), }\DecValTok{4}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Average He: 0.7904
\end{verbatim}

\hypertarget{calculate-also-the-observed-heterozygosity-for-each-str.-plot-observed-against-expected-heterozygosity-using-all-strs.-what-do-you-observe}{%
\subsection{5. Calculate also the observed heterozygosity for each STR.
Plot observed against expected heterozygosity, using all STRs. What do
you
observe?}\label{calculate-also-the-observed-heterozygosity-for-each-str.-plot-observed-against-expected-heterozygosity-using-all-strs.-what-do-you-observe}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{compute\_h0\_str }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(allele1, allele2) \{}
\NormalTok{  valid }\OtherTok{\textless{}{-}} \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(allele1) }\SpecialCharTok{\&} \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(allele2)}
  \FunctionTok{mean}\NormalTok{(allele1[valid] }\SpecialCharTok{!=}\NormalTok{ allele2[valid])}
\NormalTok{\}}


\NormalTok{h0\_str }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(str\_names, }\ControlFlowTok{function}\NormalTok{(s) \{}
  \FunctionTok{compute\_h0\_str}\NormalTok{(str\_df[[}\FunctionTok{paste0}\NormalTok{(s, }\StringTok{"{-}1"}\NormalTok{)]], str\_df[[}\FunctionTok{paste0}\NormalTok{(s, }\StringTok{"{-}2"}\NormalTok{)]])}
\NormalTok{\})}


\FunctionTok{plot}\NormalTok{(he\_str, h0\_str,}
     \AttributeTok{xlab =} \StringTok{"Expected heterozygosity (He)"}\NormalTok{,}
     \AttributeTok{ylab =} \StringTok{"Observed heterozygosity (H0)"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"H0 vs He per STR"}\NormalTok{,}
     \AttributeTok{pch =} \DecValTok{19}\NormalTok{, }\AttributeTok{col =} \StringTok{"steelblue"}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{pract_1_anna_files/figure-latex/unnamed-chunk-14-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fis }\OtherTok{\textless{}{-}}\NormalTok{ (he\_str }\SpecialCharTok{{-}}\NormalTok{ h0\_str) }\SpecialCharTok{/}\NormalTok{ he\_str}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Mean Fis:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(fis, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\DecValTok{4}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Mean Fis: -0.0024
\end{verbatim}

Answer: Most points fall near the diagonal.

\hypertarget{compare-overall-the-results-you-obtained-for-the-snp-database-with-those-you-obtained-for-the-str-database.-what-differences-do-you-observe-between-these-two-types-of-genetic-markers}{%
\subsection{6. Compare, overall, the results you obtained for the SNP
database with those you obtained for the STR database. What differences
do you observe between these two types of genetic
markers?}\label{compare-overall-the-results-you-obtained-for-the-snp-database-with-those-you-obtained-for-the-str-database.-what-differences-do-you-observe-between-these-two-types-of-genetic-markers}}

Answer:

The SNPs has more than 18000 markers, and show a mean expected
heterozygosity of only 0.31 and a mix of rare and common variants. The
STR database, by contrast, contains just 29 markers but each one is
highly multi-allelic. This allows STRs to reach much higher
heterozygosity levels, with a mean expected heterozygosity of 0.79.

Both databases show observed heterozygosity very close to expected, with
mean values near zero, indicating that both are approximately in
equilibrium. However, the variability of heterozygosity differs in each:
SNPs show a std of \textasciitilde0.16 and STRs \textasciitilde{} 0.07.
This indicates that SNPs mutate slowly and accumulate rare variants,
while STRs mutate rapidly and maintain many alleles at similar
frequencies.

\end{document}
